# Site settings
title: Plotter Projects
email: reccanti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of graphs made using Plotter.js
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  TheVirtualHeart

# Build settings
markdown: kramdown
